/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skymail;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.StringTokenizer;
import javax.swing.JTable;

/**
 *
 * @author chetan
 */
public class accPrefernace extends javax.swing.JDialog {

    /**
     * Creates new form accPrefernace
     */
    module ml=new module();
   String accMail;
  int record;
    Statement st;
    ResultSet rs;
    dlAccount dl=new dlAccount(new javax.swing.JFrame(),true);
    public int accDef=0;
    int row=-1;
    public accPrefernace(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ml.conn();
        ml.accDtl(tblAcc);
        btnEdit.setEnabled(false);
        btnRemove.setEnabled(false);
        btnSetDefault.setEnabled(false);
        tblAcc.getColumnModel().getColumn(0).setPreferredWidth(250);
         
        checkSingleAcc();
        setDef();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcc = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnSetDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SkyMail Account Preferances");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Name", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAcc);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSetDefault.setText("Set As Default");
        btnSetDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnRemove)
                    .addComponent(btnSetDefault))
                .addGap(20, 20, 20))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(101, 101, 101))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnClose, btnEdit, btnRemove, btnSetDefault});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSetDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        dl.tag=0;
        dl.clearAll();
        dl.setVisible(true);
      
        ml.accDtl(tblAcc);
        checkSingleAcc();
        setDef();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int md=JOptionPane.showConfirmDialog(this, "Are you Sure to Remove?","Confirmation",JOptionPane.OK_CANCEL_OPTION);
        if(md==JOptionPane.OK_OPTION)
        {
        try
        {
            st=ml.con.createStatement();
            StringTokenizer stk=new StringTokenizer(accMail, " ");
            while(stk.hasMoreTokens())
            {
                accMail=stk.nextElement().toString();
                
                break;
            }
            
            st.executeUpdate("delete from dbskymail.tbaccount where acc_mail='"+ accMail +"'");
            JOptionPane.showMessageDialog(this, "Account Removed Successfully");

            ml.accDtl(tblAcc);
            checkSingleAcc();
            setDef();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    
    private void tblAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccMouseClicked
        // TODO add your handling code here:
        btnEdit.setEnabled(true);
        btnRemove.setEnabled(true);
        btnSetDefault.setEnabled(true);
        try
        {
            row=tblAcc.getSelectedRow();
            accMail=(tblAcc.getModel().getValueAt(row, 0).toString());
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        ml.setDisDef(btnSetDefault, accMail);

        try
                         {
                        // System.out.println("Mouse Click"+accMail);
                         
                         StringTokenizer stk=new StringTokenizer(accMail, " ");
                            while(stk.hasMoreTokens())
                            {
                                accMail=stk.nextElement().toString();

                                break;
                            }
                         
                         
                         st=ml.con.createStatement();
                         rs=st.executeQuery("select acc_id from dbskymail.tbaccount where acc_mail='"+ accMail +"'");
                         rs.last();
                         dl.accID=Integer.parseInt(rs.getString("acc_id"));
                         //System.out.println("Acc ID while Mouse Click"+dl.accID);
                        
                         }catch(Exception ex)
                         {
                             JOptionPane.showMessageDialog(this, ex);
                         }  
    }//GEN-LAST:event_tblAccMouseClicked
    
   private void checkSingleAcc()
   {
       try
       {
           st=ml.con.createStatement();
           rs=st.executeQuery("select count(*) as id from dbskymail.tbaccount");
           rs.last();
           record=rs.getInt("id");
          
           if(record==1)
           {
               st=ml.con.createStatement();
               st.executeUpdate("update dbskymail.tbaccount set status="+ 1 +"");
                       
           }
       }catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null, ex);
       }
   }
    
    private void setDef()
    {
        try
        {
          
            st=ml.con.createStatement();
            rs=st.executeQuery("select acc_mail from dbskymail.tbaccount where status="+ 1 +"");
            rs.last();
            String accMailDef=rs.getString("acc_mail");
            
            if(row==-1)
            {   
//                System.out.println("Entered in -1 if");
//                System.out.println(tblAcc.getModel().getRowCount());
                
                for(int i=0;i<tblAcc.getModel().getRowCount();i++)
                {
                    if(accMailDef.equals(tblAcc.getModel().getValueAt(i, 0).toString()))
                    {
                        row=i;
//                        System.out.println("new row="+row);
                    }
                }
            }
//            System.out.println(row);
            //String accMailDef=accType;
            
            accMailDef+=" (Default)";
            tblAcc.getModel().setValueAt(accMailDef,row,0);
            tblAcc.getColumnModel().getColumn(0).setPreferredWidth(250);
      
            
            
        }
        catch(Exception ex)
        {
           
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        dl.fetchAcc(accMail);
        //System.out.println("BtnEdit "+accMail);
        dl.setVisible(true);
        ml.accDtl(tblAcc);
        row=-1;
        setDef();
       
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSetDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDefaultActionPerformed
        // TODO add your handling code here:
        try
        {
            st=ml.con.createStatement();
            st.executeUpdate("update dbskymail.tbaccount set status="+ 0 +"");
            st=ml.con.createStatement();
            st.executeUpdate("update dbskymail.tbaccount set status="+ 1 +" where acc_mail='"+ accMail +"'");
            //accDef=1;
            
            ml.accDtl(tblAcc);
            setDef();
        }catch(Exception ex)
        {
            
        }
        
    }//GEN-LAST:event_btnSetDefaultActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        setDef();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accPrefernace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accPrefernace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accPrefernace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accPrefernace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                accPrefernace dialog = new accPrefernace(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSetDefault;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tblAcc;
    // End of variables declaration//GEN-END:variables

    private String StringTokenizer(String accMail, String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
