/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skymail;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.StringTokenizer;
/**
 *
 * @author chetan
 */
public class dlAccount extends javax.swing.JDialog {

    /**
     * Creates new form dlAccount
     */
    module ml=new module();
    PreparedStatement pst;
    ResultSet rs;
     Statement st;
     public int tag=0;
   public  int accID;
     
    public dlAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        spInPort.setValue(143);
        spOutPort.setValue(25);
        ml.conn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpwd = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbtype = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtinchost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spInPort = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtOutHost = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        spOutPort = new javax.swing.JSpinner();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Skymail New Account Creation");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identity Information"));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Email Address");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtname)
                    .addComponent(txtemail)
                    .addComponent(txtpwd, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtemail, txtpwd});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtemail, txtname, txtpwd});

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Incoming Server Properties"));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Type");

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IMAP", "POP3" }));
        cmbtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtypeItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Host");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Port No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtinchost, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spInPort)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtinchost, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(spInPort, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Outgoing Server Properties"));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Host");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Port No");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtOutHost, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(spOutPort, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtOutHost, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(spOutPort, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnOk)
                .addGap(57, 57, 57)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtypeItemStateChanged
        // TODO add your handling code here:
        inPort();
    }//GEN-LAST:event_cmbtypeItemStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        saveAcc();
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                        try
                         {
                             
                         st=ml.con.createStatement();
                         rs=st.executeQuery("select acc_id from dbskymail.tbaccount where acc_mail='"+ txtemail.getText() +"'");
                         rs.last();
                         accID=Integer.parseInt(rs.getString("acc_id"));
                         //System.out.println("Acc ID while Opening Window "+accID);
                        
                         }catch(Exception ex)
                         {
                            // JOptionPane.showMessageDialog(this, ex);
                         }  
    }//GEN-LAST:event_formWindowOpened
    private void saveAcc()
    {
        if(txtname.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter Your Name");
            txtname.requestFocus();
        }
        else if(txtemail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter Email Address");
            txtemail.requestFocus();
            
        }
        else if(ml.validEmail(txtemail.getText().toString())==false)
        {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Email Address");
            txtemail.requestFocus();
            
        }
        else if(txtpwd.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter Password");
            txtpwd.requestFocus();
        }
        else if(txtinchost.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter Incoming Host Address");
            txtinchost.requestFocus();
        }
        else if(txtOutHost.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter Outgoing Host Address");
            txtOutHost.requestFocus();
        
        }
        else
        {   
            
            
                
               if(tag==1)
                     {
                         
                         
                         try
                         {
                          String sql;
                         sql = "update dbskymail.tbaccount set acc_name='"+ txtname.getText() +"',acc_mail='"+ txtemail.getText() +"',acc_pwd='"+ txtpwd.getText() +"',acc_type='"+ cmbtype.getSelectedItem() +"',acc_inchost='"+ txtinchost.getText() +"',acc_outhost='"+ txtOutHost.getText() +"',inport="+ spInPort.getValue() +",outport="+ spOutPort.getValue() +" where acc_id="+ accID +"";
                         pst=ml.con.prepareStatement(sql);
                         pst.execute();
                         JOptionPane.showMessageDialog(this, "Account Updated Successfully");
                         dispose();
                         }
                         catch(Exception ex)
                         {
                         JOptionPane.showMessageDialog(this, ex);
                         }
                         
                         
                         
                     }
               
               else
              
               {
                         
                try
                {
                    st=ml.con.createStatement();
                    rs=st.executeQuery("select count(*) as no from dbskymail.tbaccount where acc_mail='"+ txtemail.getText() +"'");
                    rs.last();
//                    System.out.println(rs.getInt("no"));
                if(rs.getInt("no")>0)
                    {
                        JOptionPane.showMessageDialog(this,"Account is Already Exist");
                        clearAll();
                    }
                else if(rs.getInt("no")==0)
                    {
                        
                        st=ml.con.createStatement();
                        rs=st.executeQuery("select count(*) as id from tbaccount");
                        rs.last();
                        if(rs.getInt("id")==0)
                        {
                         String sql="insert into dbskymail.tbaccount(acc_name,acc_mail,acc_pwd,acc_type,acc_inchost,acc_outhost,inport,outport,status) values('"+ txtname.getText() +"','"+ txtemail.getText() +"','"+txtpwd.getText() +"','"+ cmbtype.getSelectedItem() +"','"+txtinchost.getText() +"','"+ txtOutHost.getText() +"',"+ spInPort.getValue() +","+ spOutPort.getValue() +","+ 1 +")";
                         pst=ml.con.prepareStatement(sql);
                         pst.execute();
                           
                        }
                        else if(rs.getInt("id")>0)
                        {
                         String sql="insert into dbskymail.tbaccount(acc_name,acc_mail,acc_pwd,acc_type,acc_inchost,acc_outhost,inport,outport) values('"+ txtname.getText() +"','"+ txtemail.getText() +"','"+txtpwd.getText() +"','"+ cmbtype.getSelectedItem() +"','"+txtinchost.getText() +"','"+ txtOutHost.getText() +"',"+ spInPort.getValue() +","+ spOutPort.getValue() +")";
                         pst=ml.con.prepareStatement(sql);
                         pst.execute();
                            
                        }
                        
                         
                         JOptionPane.showMessageDialog(this, "Account Created Successfully");
                         
                         dispose();
                    }
                }
                
               catch(Exception ex)
                    {
                    JOptionPane.showMessageDialog(this, ex);
                    }
               
              }
                
            
            
        }
        
    }
    public void clearAll()
    {
        txtname.setText("");
        txtemail.setText("");
        txtpwd.setText("");
        txtinchost.setText("");
        txtOutHost.setText("");
        cmbtype.setSelectedIndex(0);
        spInPort.setValue(143);
        spOutPort.setValue(25);
        txtname.requestFocus();
    }
    public void fetchAcc(String acc)
    {
        try
        {   tag=1;
            StringTokenizer stk=new StringTokenizer(acc, " ");
            while(stk.hasMoreTokens())
            {
                acc=stk.nextElement().toString();
                
                break;
            }
//            System.out.println("While Fetching"+acc);
            st=ml.con.createStatement();
            rs=st.executeQuery("select * from dbskymail.tbaccount where acc_mail='"+ acc +"'");
            
            
            while(rs.next())
            {
               txtname.setText(rs.getString("acc_name"));
               txtemail.setText(rs.getString("acc_mail"));
               txtpwd.setText(rs.getString("acc_pwd"));
               txtinchost.setText(rs.getString("acc_inchost"));
               txtOutHost.setText(rs.getString("acc_outhost"));
               cmbtype.setSelectedItem(rs.getString("acc_type"));
               spInPort.setValue(rs.getInt("inport"));
               spOutPort.setValue(rs.getInt("outport"));
            }
            
        }
        catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex);
            }
        
    }
    private void inPort()
    {
        if(cmbtype.getSelectedItem().equals("IMAP"))
        {
            spInPort.setValue(143);
        }
        else if(cmbtype.getSelectedItem().equals("POP3"))
        {
            spInPort.setValue(995);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlAccount dialog = new dlAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner spInPort;
    private javax.swing.JSpinner spOutPort;
    private javax.swing.JTextField txtOutHost;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtinchost;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpwd;
    // End of variables declaration//GEN-END:variables
}
